# Generated by Django 4.2.4 on 2023-08-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(default="default.png", upload_to="services"),
        ),
        migrations.AlterField(
            model_name="recentwork",
            name="image",
            field=models.ImageField(default="default.png", upload_to="works"),
        ),
    ]
